FROM python:3.12

COPY app /builds/app/

RUN pip install --no-cache-dir -r /builds/app/requirements.txt \
    && rm -f /builds/app/*.txt \
    && find / -type d -name __pycache__ -prune -exec rm -rf {} \;

WORKDIR /builds/app

CMD ["uvicorn", "entry:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]